#! /bin/bash

habsdir=$1

for d in ${habsdir}/habs/*; do
    . ${d}/PKGBUILD
    case $_hkgname in
        (Agda|Agda-executable)
            ;;
        (*)
            echo ${_hkgname},${pkgver}
            ;;
    esac
done
